version: '3.3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: yarn start
    ports:
      - "8081:8080"
    volumes:
      
      - "~/.bash_history:/.bash_history"
      - "./:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"